# Generated by Django 2.2.24 on 2021-06-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0122_auto_20210624_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pricing',
            field=models.SmallIntegerField(default=1, verbose_name='Pricing'),
        ),
        migrations.AlterField(
            model_name='problemtranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('vi', 'Vietnamese')], max_length=7, verbose_name='language'),
        ),
    ]
