# Generated by Django 2.2.24 on 2021-06-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0123_auto_20210629_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='pricing',
            field=models.SmallIntegerField(choices=[(1, 'Free'), (2, 'Premium'), (3, 'Premium+')], default=1, verbose_name='Pricing'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pricing',
            field=models.SmallIntegerField(choices=[(1, 'Free'), (2, 'Premium')], default=1, verbose_name='Pricing'),
        ),
    ]
