# Generated by Django 2.2.24 on 2021-07-07 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0124_auto_20210629_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemtranslation',
            name='language',
            field=models.CharField(choices=[('vi', 'Vietnamese')], max_length=7, verbose_name='language'),
        ),
    ]
